"""
Problem 2 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""
i = 0
fib_series = 0
total_even_val = 0
def fib_sum(i):
    if i <= 2:
        return i
    else:
        result = fib_sum(i-1)+fib_sum(i-2)
        return result

for i in range(0, 4000000, 1):
        fib_series = fib_sum(i)
        print fib_series
        if fib_series % 2 == 0:
            total_even_val+=fib_series
        else:
            continue
print ("sum of even fib_series upto" + " " + str(int(i)) + " " + "is" + " " + str(int(total_even_val)))