"""
Problem 2 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""
a=1
b=2
c=0
print(a,b)
total_even_val=2
for i in range (2,(4000000-1)):
    c=b+a
    print(str(c))
    a=b
    b=c
    if c%2==0:
        total_even_val+=c
        continue

print("sum of even-valued terms of fibonacci seq upto 4 million:",total_even_val)
